# Generated by Django 6.0.6 on 2026-07-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_purchasebill_purchasebilldetail_purchaseitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseBillDetail',
            new_name='PurchaseBillDetails',
        ),
    ]
