# Generated by Django 6.0.6 on 2026-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
